<?php

return [
    'support'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au  <a href="tel:07 60 17 26 80">07 60 17 26 80</a> ou <a href="mailto:support@mail.mycontactopticien.com">support@mail.mycontactopticien.com</a>.',
    'confirmation' => [
        'opticien'      =>'opticien',
        'de'            =>'de',
        'title'         =>'Programme MyContACt ',
        'txt_blue'      =>'Bonjour,<br>
                            Pour finaliser votre inscription<br>
                            merci de cliquer sur le lien ci-dessous...<br>',

        'txt_dark'      =>'Pour sécuriser votre inscription nous allons vous envoyer un <b>SMS avec un code.</b>
                            Merci de vous munir de votre téléphone mobile.',
        'btn'           =>'Finaliser votre inscription',
        'footer'         =>'Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous.',
    ],

    'mail_first_connexion' => [
        'opticien'      =>'opticien',
        'de'            =>'de',
        'title'         =>'Programme MyContACt ',
        'txt_blue'      =>'Bravo !<br/>Vous êtes maintenant inscrits<br/>à la plateforme<br/>Opticien MyContact',

        'txt_dark'      =>'Cliquez sur le lien ci-dessous pour accéder à votre compte et commencer à animer la clientèle ACUVUE<sup>®</sup> de votre point de vente',
        'btn'           =>'Je me connecte',
        'footer'         =>'Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous. Des Packs confort et Packs manipulations pour améliorer votre expérience lentilles au quotidien, dispensés chez votre opticien sur rendez-vous.',
    ],
        //{!! __('optician/mail.MMO1_Finalisation_de_votre_inscription.') !!}
    'MMO1_Finalisation_de_votre_inscription'    => [
        'subject'          => 'MyContACt by ACUVUE® - Finalisation de votre inscription',
        'title'            =>'FINALISATION DE VOTRE INSCRIPTION',
        'section1_p1'      => 'Vous avez commencé le parcours de votre inscription à MyContACt by ACUVUE<sup>®</sup>, vous vous êtes arrêté à l’étape 2.',
        'section1_p2'      =>'Nous vous invitons à finaliser l’inscription en cliquant sur le lien ci-dessous.',
        'section2_p1'      => 'Les données que vous avez renseignées à l’étape 1 ont été sauvegardées. Elles seront effacées dans 48 heures si vous ne finalisez pas votre inscription.',
        'CTA'              => 'JE FINALISE MON INSCRIPTION',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail .',
        'Cordialement'      => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup>sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup>OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
        //{!! __('optician/mail.MMO2_Finalisation_de_votre_inscription.') !!}
    'MMO2_Finalisation_de_votre_inscription'    => [
        'title'            => 'FINALISATION DE VOTRE INSCRIPTION',
        'subject'          => 'MyContACt by ACUVUE® - Finalisation de votre inscription',
        'section1_p1'      => 'Vous avez commencé le parcours de votre inscription à MyContACt by ACUVUE<sup>®</sup>, Vous vous êtes arrêtés avant la dernière étape.',
        'section1_p2'      => 'Nous vous invitons à finaliser l’inscription en cliquant sur le lien ci-dessous.',
        'section2_p1'      => 'Les données que vous avez renseignées à l’étape 1 ont été sauvegardées. Elles seront effacées dans 48 heures si vous ne finalisez pas votre inscription.',
        'CTA'              => 'JE FINALISE MON INSCRIPTION',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup>sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup>OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
        //{!! __('optician/mail.MMO3_Inscription_validée.') !!}
    'MMO3_Inscription_valide'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Inscription validée',
        'title'            => 'INSCRIPTION VALIDÉE',
        'section1_p1'      => 'Félicitations, vous êtes maintenant :inscrit à la plateforme MyContACt by ACUVUE<sup>®</sup>.',
        'section1_p2'      => 'Cliquez sur le lien ci-dessous pour accéder à votre compte et commencer à animer la clientèle ACUVUE<sup>®</sup> de votre point de vente.',
        'section2_p1'      => 'Les données que vous avez renseignées à l’étape 1 ont été sauvegardées. Elles seront effacées dans 48 heures si vous ne finalisez pas votre inscription.',
        'CTA'              => 'JE ME CONNECTE',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
        //{!! __('optician/mail.MMO4-Votre_magasin_vousinvite_rejoindre_sa_plateforme.') !!}
    'MMO4-Votre_magasin_vousinvite_rejoindre_sa_plateforme'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Votre magasin vous invite à rejoindre sa plateforme',
        'title'            => 'VOTRE MAGASIN VOUS INVITE À REJOINDRE MyContACt by ACUVUE<sup>®</sup>',
        'section1_p1'      => 'Bienvenue sur la plateforme MyContACt by ACUVUE<sup>®</sup> de votre magasin :opticien - :ville :CP  !',
        'section1_p2'      => 'Vos identifiants pour vous connecter sur la plateforme sont les suivants :
           <br> Votre identifiant : :login ',
        'section2_p1'      => 'Les données que vous avez renseignées à l’étape 1 ont été sauvegardées. Elles seront effacées dans 48 heures si vous ne finalisez pas votre inscription.',
        'CTA'              => 'je termine mon inscription',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
        //{!! __('optician/mail.MMO5_Nouveau_mot_de_passe.') !!}
    'MMO5_Nouveau_mot_de_passe'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Nouveau mot de passe',
        'title'            => 'NOUVEAU MOT DE PASSE',
        'section1_p1'      => 'Votre mot de passe a été modifié.',
        'section1_p2'      => 'Veuillez trouver ci-dessous vos identifiants pour vous connecter sur la plateforme :
                                <br> Votre identifiant : :login ',
        'section2_p1'      => 'Les données que vous avez renseignées à l’étape 1 ont été sauvegardées. Elles seront effacées dans 48 heures si vous ne finalisez pas votre inscription.',
        'CTA'              => 'JE ME CONNECTE',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO6_Mot_de_passe_oublié.') !!}
    'MMO6_Mot_de_passe_oublié'    => [
        'Bonjour'          => 'Bonjour',
        'title'            => 'MOT DE PASSE OUBLIÉ',
        'subject'          => 'MyContACt by ACUVUE® - Mot de passe oublié',

        'section1_p1'      => 'Vous avez oublié votre mot de passe MyContACt by ACUVUE<sup>®</sup> ? Pas de problème ! Ce sont des choses qui arrivent. ',
        'section1_p2'      => 'Si vous êtes à l\'origine de cette demande, et si vous êtes toujours d\'accord pour obtenir un nouveau mot de passe, il vous suffit de cliquer sur le lien ci-dessous, ou de le recopier dans votre navigateur.',
        'section1_p3'      => 'Vous serez alors redirigé vers une page sécurisée où vous devrez renseigner votre identifiant.',
        'CTA'              => 'OBTENIR UN NOUVEAU MOT DE PASSE',
        'section2_p1'      => 'Cette demande a été effectuée à partir de l\'IP :ip',
        'section2_p2'      => 'Ce lien est valable uniquement une heure. Passé ce délai, vous devrez faire une nouvelle demande. Il sera nécessaire de cliquer sur le lien « Mot de passe oublié ».',
        'section2_p3'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Nous vous remercions pour toute la confiance que vous accordez à MyContACt by ACUVUE<sup>®</sup>  et restons à votre disposition.<br/><br/>Cordialement,',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
     //{!! __('optician/mail.MMO7-Votre_mot_de_passe.') !!}
     'MMO7-Votre_mot_de_passe'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Votre mot de passe ',

        'title'            => 'VOTRE MOT DE PASSE',
        'section1_p1'      => 'Votre mot de passe pour accéder à la plateforme de votre MyContACt by ACUVUE<sup>®</sup> de votre magasin est  :',
        'CTA'              => 'JE ME CONNECTE',
        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
        <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO8_Un_nouveau_client.') !!}
    'MMO8_Un_nouveau_client'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Un nouveau client vient de s\'inscrire au programme ',

        'title'            => 'UN NOUVEAU CLIENT VIENT DE S\'INSCRIRE AU  PROGRAMME',
        'section1_p1'      => 'Le client :civ :name vient de rejoindre le programme MyContACt by ACUVUE<sup>®</sup> de votre point de vente :opticien - :ville :CP',
        'section1_p2'      => 'Nous venons de vous envoyer une notification dans votre manager. ',
        'section2_p1'      => 'Vous devez dès à présent glisser une facture attestant que votre client est bien un porteur ACUVUE<sup>®</sup> afin de finaliser son inscription.',
        'section2_p2'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO9_inscription_nouveau_client_non_conforme.') !!}
    'MMO9_inscription_nouveau_client_non_conforme'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Inscription nouveau client non-conforme',
        'title'            => 'Inscription nouveau client non-conforme',
        'section1_p1'      => 'La facture que vous avez déposée pour inscrire votre client :civ :name n\'est pas conforme pour le motif suivant :',
        'section1_p2'      => 'La facture est trop ancienne',
        'section1_p3'      => 'Nous vous invitons à corriger la particpation si vous souhaitez que votre client :civ :name rejoigne le programme.
                                Merci de votre compréhension.',
        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'section2_p2'      => 'Merci de votre compréhension.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO10_confirmation_de_votre_rendez-vous.') !!}
    'MMO10_confirmation_de_votre_rendez-vous'    => [
        'Bonjour'          => 'Bonjour',
        'title'            => 'Confirmation rendez-vous client dans votre point de vente ',
        'section1_p1'      => 'Vous avez rendez-vous avec :civ :name le :date à :heure.',
        'section1_p2'      => 'Une notification vous a été envoyée dans votre espace "MON ACTIVITÉ".',
        'subject'          => 'MyContACt by ACUVUE® - Confirmation rendez-vous client dans votre point de vente ',

        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi.:num',
        'section2_p2'      => 'Merci de votre compréhension.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO11-facturation_services.') !!}
    'MMO11-facturation_services'    => [
        'Bonjour'          => 'Bonjour',
        'title'            => 'FACTURATION SERVICES',
        'section1_p1'      => 'Veuillez valider votre facture du mois de :mois dans votre espace "MON ACTIVITÉ" pour que nous puissions la payer selon les modalités de règlement convenues.',

        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'section2_p2'      => 'Merci d\'avance de votre dilligence.',
        'subject'          => 'MyContACt by ACUVUE® - Facturation services ',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    'MMO11-releve_remboursement'    => [
        'Bonjour'          => 'Bonjour',
        'title'            => 'RELEVÉ OFFRES DE REMBOURSEMENT',
        'section1_p1'      => 'Veuillez valider votre relevé du mois de :mois dans votre espace "MON ACTIVITÉ" pour que nous puissions la payer selon les modalités de règlement convenues.',

        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'section2_p2'      => 'Merci d\'avance de votre dilligence.',
        'subject'          => 'MyContACt by ACUVUE® - Relevé offres de remboursement ',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO12-Relance_facturation_services.') !!}
    'MMO12-Relance_facturation_services'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Relance : facturation services ',
        'title'            => 'RELANCE : FACTURATION SERVICES',
        'section1_p1'      => 'Merci de bien vouloir valider votre facture du mois de :mois dans votre espace « MON ACTIVITÉ » pour que nous puissions la régler selon les modalités convenues.',
        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'section2_p2'      => 'Merci d\'avance de votre dilligence.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    'MMO12-Relance_facturation_releve'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Relance : relevé ',
        'title'            => 'RELANCE : RELEVÉ',
        'section1_p1'      => 'Merci de bien vouloir valider votre relevé du mois de :mois dans votre espace « MON ACTIVITÉ » pour que nous puissions la régler selon les modalités convenues.',
        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',
        'section2_p2'      => 'Merci d\'avance de votre dilligence.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO13-Règlement_offres_de_remboursement.') !!}
    'MMO13-Reglement_offres_de_remboursement'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE® - Règlement Offres de remboursement ',
        'title'            => 'RÈGLEMENT OFFRES DE REMBOURSEMENT ',
        'section1_p1'      => 'Nous avons viré sur le compte bancaire que vous avez renseigné dans votre manager MyContACt by ACUVUE<sup>®</sup>, la somme de :montant euros en compensation des offres de remboursement conformes de votre point de vente pour la période du :jour_debut au :jour_fin :mois :année.',
        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],
    //{!! __('optician/mail.MMO14-Réglement_services.') !!}
    'MMO14-Réglement_services'    => [
        'Bonjour'          => 'Bonjour',
        'subject'          => 'MyContACt by ACUVUE®  - Règlement Services dispensés',
        'title'            => 'RÈGLEMENT SERVICES ',
        'section1_p1'      => ' Nous avons effectué le virement bancaire que vous avez renseigné dans votre manager MycontACt by ACUVUE<sup>®</sup>, la somme de :montant euros en compensation des services dispensés dans votre point de vente pour la période du :jour_debut au :jour_fin :mois :année.',

        'section2_p1'      => 'Si vous avez besoin d’assistance, notre centre de support est assuré de 8:30 à 19:00 du lundi au vendredi et de 9:00 à 13:00 le samedi. Vous pouvez contacter ce service au :num ou :mail.',

        'Cordialement'     => 'Cordialement,<br/>L’équipe MyContACt by ACUVUE<sup>®</sup>',
        'footer'           => 'Conformément au Règlement Général à la Protection des Données (RGPD) n°2016/679 et à la loi Informatique et Libertés modifiée, vous disposez d’un droit d’accès, de rectification, de suppression de vos données pour motif légitime ainsi que du droit à la portabilité de vos données, du droit à la limitation du traitement des données vous concernant ainsi que du droit au retrait de votre consentement que vous pouvez exercer en écrivant à privacymddfrance@ITS.JNJ.com. Pour plus d’informations sur vos droits, nous vous invitons à consulter notre Politique de confidentialité.
                                <br><br>Les lentilles de contact ACUVUE<sup>®</sup> sont destinées aux amétropies sous réserve d’une prescription médicale. Les lentilles de contact ACUVUE<sup>®</sup> OASYS with Transitions™ sont des lentilles photochromiques indiquées également pour atténuer une luminosité élevée grâce à l’agent photochromique qui absorbe activement la lumière visible. Avant toute utilisation, se référer à la notice d’utilisation qui accompagne le dispositif et respecter les consignes d’utilisation y figurant et figurant sur l’étiquetage pour connaître les indications, les contre-indications, les effets secondaires, l’utilisation recommandée, les mises en garde et les précautions. Toutes les lentilles de contact de la marque ACUVUE<sup>®</sup> possèdent un filtre UV de Classe 1 ou 2, aidant à protéger la cornée et l’intérieur de l’œil des rayons UV nocifs. Les lentilles de contact avec filtre UV ne peuvent se substituer à une protection oculaire absorbant les UV telle que les lunettes de soleil classiques ou avec coques latérales car elles ne recouvrent pas l’intégralité des tissus oculaires annexes. Ce dispositif médical est un produit de santé réglementé qui porte, au titre de cette réglementation, le marquage CE. Mandataire européen : AMO Ireland (Irlande). ACUVUE®, 1-DAY ACUVUE<sup>®</sup> Moist, ACUVUE<sup>®</sup> OASYS 1-Day, ACUVUE<sup>®</sup> OASYS et ACUVUE<sup>®</sup> OASYS with Transitions™ sont des marques de Johnson & Johnson Medical SAS, 1 rue Camille Desmoulins 92787 Issy-les-Moulineaux Cedex 9. RCS Nanterre B 612 030 619. Document réservé à l\'usage des professionnels de santé. © Johnson & Johnson Medical SAS 2020. PP-XX-XX-XX. Mai 2020.'
    ],


];

